spring:
  main:
    web-application-type: reactive

server:
  port: 4000

polyflix:
  services:
    legacy: "http://localhost:4001/"
    note: "http://localhost:5001/"
    video: "http://localhost:5002/"

