spring:
  main:
    web-application-type: reactive

server:
  port: 4000

polyflix:
  services:
    legacy: "http://localhost:5000/"
    note: "http://localhost:5001/"
    video: "http://localhost:5002/"
    quiz: "http://localhost:5003/"
    certification: "http://localhost:5004/"
    catalog: "http://localhost:5005/"
    attachment: "http://localhost:5006/"
