spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origin-patterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
  sleuth:
    otel:
      config:
        trace-id-ratio-based: 1.0
      exporter:
        otlp:
          endpoint: http://localhost:4317
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: http://localhost:3002/realms/Polyflix/protocol/openid-connect/token/introspect
          client-id: polyflix-gateway
          client-secret: GatewaySecretFromKeycloak

server:
  port: 4000

polyflix:
  services:
    legacy: "http://localhost:4001/"
    user: "http://localhost:4002/"
    note: "http://localhost:5001/"
    video: "http://localhost:5002/"
    quizz: "http://localhost:5003/"
    certification: "http://localhost:5004/"
    catalog: "http://localhost:5005/"
    attachment: "http://localhost:5006/"
    search: "http://localhost:5007"
    subtitle: "http://localhost:5008"