spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "https://v2.polyflix.dopolytech.fr"
  security:
    oauth2:
      resourceserver:
        opaquetoken:
          introspection-uri: https://sso.v2.polyflix.dopolytech.fr/realms/polyflix/protocol/openid-connect/token/introspect
          client-id: polyflix-gateway
polyflix:
  services:
    legacy: http://backend/
    note: http://note/
    video: http://video/
    quizz: http://quizz/
    certification: http://certification/
    catalog: http://catalog/
    attachment: http://attachment/
    search: http://search
    user: http://user
    subtitle: http://subtitle