spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "http://localhost:3000"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true

server:
  port: 4000

polyflix:
  services:
    legacy: "http://localhost:4001/"
    note: "http://localhost:5001/"
    video: "http://localhost:5002/"
    quizz: "http://localhost:5003/"
    certification: "http://localhost:5004/"
    catalog: "http://localhost:5005/"
    attachment: "http://localhost:5006/"
    search: "http://localhost:5007"